import { logout } from '@/lib/action';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <div>
          <ul>
            <li>
              <Link href="/">홈</Link>
            </li>
            <li>
              <Link href="/login">로그인</Link>
            </li>
            <li>
              <Link href="/register">회원가입</Link>
            </li>
            <li>
              <form action={logout}>
                <button>로그아웃</button>
              </form>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
